from typing import Any, Optional

__all__ = (
  "blue",
  "clear",
  "cyan",
  "gray",
  "green",
  "magneta",
  "randomCode",
  "red",
  "tzFilter",
  "yellow"
)

def clear() -> None: ...
def gray(*args: Any, type: int = 1) -> str: ...
def red(*args: Any, type: int = 1) -> str: ...
def green(*args: Any, type: int = 1) -> str: ...
def yellow(*args: Any, type: int = 1) -> str: ...
def blue(*args: Any, type: int = 1) -> str: ...
def magneta(*args: Any, type: int = 1) -> str: ...
def cyan(*args: Any, type: int = 1) -> str: ...
def tzFilter(hour: int = 23, gmt: Optional[int] = None) -> int: ...
def randomCode(length: int = 15, chars: Optional[str] = None) -> str: ...
